# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.kornia.org
title: Kornia
email: contact@kornia.org
author: Edgar Riba
description: > # "Write an awesome description for your new site here. 
  Kornia is a differentiable computer vision library for PyTorch.

  It consists of a set of routines and differentiable modules to solve generic computer vision problems. At its core, the package uses PyTorch as its main backend both for efficiency and to take advantage of the reverse-mode auto-differentiation to define and compute the gradient of complex functions.
copyright: 'Copyright &copy; 2019 Kornia. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: kornia_foss
    url: https://twitter.com/pytorch
  - title: github
    url: https://github.com/kornia/kornia 
